      import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar/navbar";
import { Toaster } from "react-hot-toast";
import Footer from "@/components/Footer/Footer";
import MyProvider from "@/myProvider/MyProvider";
import CartProvider from "@/context/cart.context";
import WishlistProvider from "@/context/wishlist.context";
// import WishlistProvider from "@/context/wishlist.context";

export const metadata: Metadata = {
  title: "Shop Mart",
  description: "Generated by create next app",
};


export interface LayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: LayoutProps) {
  return (
    <html lang="en">
      <body>
        <WishlistProvider>
          
        <CartProvider>
          <MyProvider>
            <Navbar />
            <div className=" px-4">
              <Toaster />
              {children}
            </div>
            <Footer />
          </MyProvider>
        </CartProvider>
        </WishlistProvider>
      </body>
    </html>
  );
}



